# Network config
audionet:
  audionet_name: BSRNN
  audionet_config:
    sample_rate: 16000
    win: 512
    stride: 128
    feature_dim: 128
    num_repeat: 12
    num_output: 2

# Loss config
loss:
  train:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_snr
    config:
      pit_from: pw_mtx
      threshold_byloss: true
  val:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false

# Training config
training:
  system: AudioLightningModule
  gpus: [0,1,2,3]
  parallel: ddp
  epochs: 500
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 30
    verbose: true
  SpeedAug: False
  
# Optim config
optimizer:
  optim_name: adam
  lr: 0.001
  weight_decay: 0

# Sche config
scheduler: 
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 15
    factor: 0.5

# Data config
datamodule:
  data_name: LRS2DataModule
  data_config:
    train_dir: DataPreProcess/LRS2/train-100
    valid_dir: DataPreProcess/LRS2/dev
    test_dir: DataPreProcess/LRS2/test
    n_src: 2
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
    batch_size: 1
    num_workers: 8
    pin_memory: true
    persistent_workers: false

exp:
  exp_name: BSRNN